config/routes.rb
Rails.application.routes.draw do

  resources :banks do
    resources :rates
  end

  resources :rates do
    resources :banks
  end

  root 'banks#index'

end

app/models/bank.rb
class Bank < ActiveRecord::Base
  has_and_belongs_to_many :rates

  def self.total_on(date)
    where("date(created_at) = ?", date).sum(:name)
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  has_and_belongs_to_many :banks
  
  scope :weekly, -> { where(:created_at => 1.week.ago..Time.now) }
  scope :dollar, -> { where(:currency => 'ДОЛЛАР') }

  def self.recent_rates
    Rate.where("created_at >= ?", 1.day.ago.utc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController

  def index
    @banks = Bank.all
  end

  def show
    @bank = Bank.find(params[:id])
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

  def index
    @rates = Rate.where("currency >= ?", params[:currency])
  end

  def show
    @rate = Rate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
  def dates_range
    (1.week.ago.to_i..DateTime.now.to_i).step(1.day).map{|t| Time.at(t).strftime('%d.%m.%Y') }
  end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/banks/index.html.erb
<% @banks.each do |bank| %>
  <table>
     <tr>
       <td><%= link_to bank.name, bank_path(bank) %></td>
     </tr>
  </table>
<% end %>

app/views/banks/show.html.erb
<h1><%= @bank.name %></h1>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $('#curr_chart').highcharts({
      chart: {
        type: 'line'
      },
      title: {
        text: "По банкам Украины"
      },
      xAxis: {
        categories: <%= @bank.rates.weekly.dollar.map {|r| r.created_at.strftime('%d.%m.%Y') }.to_json.html_safe %>
      },
      yAxis: {
        title: {
          text: "Rates"
        }
      },
      series: [{
        name: 'buy',
        data: <%= @bank.rates.weekly.dollar.map {|r| r.buy.to_f }.to_json.html_safe %>
      }, 
      {
        name: 'sale',
        data: <%= @bank.rates.weekly.dollar.map {|r| r.sale.to_f }.to_json.html_safe %>
      }]
    });
  });
</script>
<div id="curr_chart"></div>

<table>
  <thead>
    <tr>
      <td>Валюта</td>
      <td>Покупка</td>
      <td>Продажа</td>
    </tr>
  </thead>
  <tbody>
  <% @bank.rates.recent_rates.each do |rate| %>
    <tr>
      <td><%= rate.currency %></td>
      <td><%= rate.buy %></td>
      <td><%= rate.sale %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InfinitC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rates/index.html.erb
<table>
  <% @rates.each do |rate| %>
    <tr>
      <td>
         <% rate.banks.each do |bank| %>
           <%= bank.name %>
         <% end %>
      </td>
      <td><%= rate.buy %></td>
      <td><%= rate.sale %></td>
    </tr>
  <% end %>
</table>

app/views/rates/show.html.erb
<h1><%= @rate.currency %></h1>
<% @rate.banks.each do |bank| %>
    <%= bank.name %>
  <% bank.rates.each do |rate| %>
    <%= rate.currency %>
    <%= rate.buy %>
    <%= rate.sale %>
  <% end %>
<% end %>